---
- name: Ensure jq is present
  ansible.builtin.package:
    name: jq
    state: present
  become: true

- name: Ensure Github is present in known_host
  block:
    - name: Fetch github hostkeys
      ansible.builtin.shell: >
        set -o pipefail && curl --silent {{ add_github_hostkeys_api_endpoint }} |
         jq --raw-output '"github.com "+.ssh_keys[]'
      args:
        executable: /bin/zsh
      changed_when: false
      check_mode: false
      register: fetched_github_hostkeys

    - name: Add Github known host keys to the system
      ansible.builtin.include_tasks:
        file: add_keys_to_system.yaml
