---
# terraform managed
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml
driver:
  name: docker
platforms:
  - name: "{{ lookup('env', 'IMAGE_NAME') }}"
    image: "{{ lookup('env', 'REGISTRY') }}/{{ lookup('env', 'IMAGE_ID') }}:latest"
    cmd: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    privileged: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      Ubuntu:
        ansible_user: ansible
verifier:
  name: testinfra
