---
# terraform managed
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml
driver:
  name: docker
platforms:
  - name: "!!IMAGE_NAME"
    image: "quay.io/pimvh/!!IMAGE_NAME:latest"
    cmd: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    privileged: true
    pre_build_image: false
    override_command: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      Ubuntu:
        ansible_user: ansible
verifier:
  name: testinfra
