---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml
    role-file: requirements.yaml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "add_github_hostkeys-${image}-${tag}"
    image: "${namespace:-pimvh}/${image}:${tag}"
    name: Ubuntu
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
