---
# terraform managed
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml
driver:
  name: docker
platforms:
  - name: Ubuntu Jammy
    image: quay.io/pimvh/molecule-ubuntu-jammy:latest
    cmd: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    privileged: true
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      Ubuntu:
        ansible_user: ansible
verifier:
  name: testinfra
